# Document:
# http://simiki.org/docs/configuration.html

url: http://wbear2.github.io
title: Personal Wiki
keywords: linux, hadoop, java, python, javascript
description: 
author: Changyi Yuan

deploy:
  - type: git
    remote: git@github.com:wbear2/wbear2.github.io.git
    branch: source
